name: "Check changes"

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-optex:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update TeX Live
        run: |
          tlmgr update --self --all
          luatex --credits

      - name: Build and test
        run: |
          cd optex
          make format
          make test
